# Generated by Django 4.2.1 on 2023-05-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_assigned_to_task_assigned_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_user',
            new_name='assigned_to',
        ),
    ]
