# Generated by Django 4.2.1 on 2023-05-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_assigned_user_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='color',
            field=models.CharField(max_length=8),
        ),
    ]
