# Generated by Django 4.2.1 on 2023-05-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_project_color_alter_task_color_alter_taskgroup_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='statuses',
        ),
        migrations.AddField(
            model_name='status',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='tasks.project'),
            preserve_default=False,
        ),
    ]
