# Generated by Django 4.2.1 on 2023-05-28 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_status_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='color',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='tasks.project'),
        ),
    ]
