# Generated by Django 4.2.1 on 2023-05-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_community_color_alter_status_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='project',
        ),
    ]
