# Generated by Django 4.2.1 on 2023-05-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_status_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='statuses',
            field=models.ManyToManyField(related_name='projects', to='tasks.status'),
        ),
    ]
