# Generated by Django 4.2.1 on 2023-05-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_project_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='statuses',
        ),
    ]
