# Generated by Django 4.2.1 on 2023-05-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_community_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_public',
            field=models.BooleanField(default=0),
        ),
    ]
